version: "3.8"
services:
  jaeger:
    image: jaegertracing/jaeger:2.5.0
    ports:
      - "16686:16686"  # Jaeger UI
      - "14318:4318"  # Jaeger HTTP
      - "14317:4317"  # Jaeger grpc

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.96.0
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    depends_on:
      - jaeger