spring.application.name=otel_example
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
management.otlp.tracing.transport=http
management.otlp.tracing.export.enabled=true
management.tracing.sampling.probability=1.0

logging.level.io.opentelemetry.exporter.otlp=TRACE
logging.level.io.opentelemetry.sdk.trace=TRACE